name: "AI Evaluation"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  evaluate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        evaluator: 
          - name: qa
            data: qa_data.jsonl
    env:
      GENAI_EVALS_CONFIG_PATH: ${{ github.workspace }}/evaluate-config-${{ matrix.evaluator.name }}.json
      GENAI_EVALS_DATA_PATH: ${{ github.workspace }}/data/general_purpose/${{ matrix.evaluator.data }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Write evaluate config
        run: |
          evaluator_name="${{ matrix.evaluator.name }}"
          if [ "$evaluator_name" = "qa" ]; then
            evaluator_class="QAEvaluator"
          elif [ "$evaluator_name" = "coherence" ]; then
            evaluator_class="CoherenceEvaluator"
          elif [ "$evaluator_name" = "fluency" ]; then
            evaluator_class="FluencyEvaluator"
          fi

          cat > ${{ env.GENAI_EVALS_CONFIG_PATH }} <<EOF
          {
            "data": "${{ env.GENAI_EVALS_DATA_PATH }}",
            "evaluators": {
              "$evaluator_name": "$evaluator_class"
            },
            "ai_model_configuration": {
              "type": "azure_openai",
              "azure_endpoint": "${{ secrets.AZURE_OPENAI_ENDPOINT }}",
              "azure_deployment": "${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}",
              "api_key": "${{ secrets.AZURE_OPENAI_API_KEY }}",
              "api_version": "${{ secrets.AZURE_OPENAI_API_VERSION }}"
            }
          }
          EOF

      - name: Run AI Evaluation
        id: run-ai-evaluation
        uses: microsoft/genai-evals@main
        with:
          evaluate-configuration: ${{ env.GENAI_EVALS_CONFIG_PATH }}
